### PR TITLE
Swedish translation, Case insensitive blacklist, Avoid confusing letters in password generation

### PR DESCRIPTION
**Pull request by VincentNikkelen**
Swedish translation and minor bug fix Dutch translation

### CODE REVIEW

**Comment by VincentNikkelen** [comment]
Sorry, wanted to make a separate pull-request for the case insensitive passwords but as I am new with GitHub, I have no clue how to do that.

Up to you if you want to reject of accept this one. Let me know what I can do.

**Comment by VincentNikkelen** [comment]
Hmm, now I did it again with the letters. Really sorry.

I think I will go hiding somewhere in a deep hole until I have found and read a good explanation on how to do this GitHub thing.

**Comment by antelle** [comment]
Thank you!
I'll review and merge the changes tomorrow, when I return to my computer and have some time.
That's not a problem, okay, let it all be in one pull request.

**Comment by antelle** [comment]
I have merged new translation and features, thanks a lot!
They are for now just in master, I'm going to release them at the weekend, when I also make some refactoring.
Also .editorconfig is now here, so when you update, text editors will guide you to insert consistent whitespaces (I use spaces for this project, not tabs).
Avoiding visually similar letters is very cool feature, thank you!

**Comment by VincentNikkelen** [comment]
I'll have a look at .editorconfig. Sorry for using tabs, will try to improve on that.

As I am not very experienced in JS, I was wondering if you could clarify the following.

Does JS do any code optimizations? In the code making passwords check against the blacklist I use pass.toLower in the loop guard. Compilers will move this outside the loop for efficiency, but I do not know if JS does the same. Would be otherwise good to do this once before the loop to avaoid making the toLower() call frequently.

**Comment by antelle** [comment]
Most of javascript engines will not make optimizations for this case. You are right, it's better to move this outside the loop (although here the black list is very small and performance will not degrade much).
For Javascript, there's awesome jsperf site which can create, run and share benchmarks and show statistics. Here I have created a test which shows that having toLower outside of the loop is much faster: 
http://jsperf.com/tolowercase-inside-and-outside-the-loop

**Comment by VincentNikkelen** [comment]
Thanks, learned something new today so it is a good day ;-)

Really appreciated the additional info you provided.

**Comment by VincentNikkelen** [comment]
Great, did some experimenting with jsperf and it works great.

Did some experimenting with it and learned a lot. Thanks for the info.

**Comment by VincentNikkelen** [comment]
I know, this is an old discussion but interesting to see the performance results for current browsers. The performance gain has disappeared, clearly showing how well javascript has improved in the optimization area.

**Pull request merged**
